### ISSUE TITLE
Version the Docs and keep tight updates with QPC releases

### ISSUE THREAD

**Issue by justinkreft** [quipucords/quipudocs#101]
Our customers often use versions that are older than bleeding edge releases.

With new features coming out at each milestone, and the need to maintain different install instructions for different RHEL versions (EPEL for 6, etc), the documentation should be versioned upon every release of QPC with the ability to see old release documentation. This is very important to end users, because it isn't always guaranteed that a customer will use the latest release.

Maintaining a tight loop between documentation and feature releases is critical for downstream partners.

As an illustration, (and I will make separate issues for these upon 0.9.2 release), but latest pre-release contains two features (masking report columns with hash, and adding a file hash to reports to ensure veracity of the file being transferred). These, for example, need to be proactively documented, but old versions of documentation (0.9.1) should be maintained because some customers may be using them in the wild.

I _DO NOT_ think we should maintain documentation for versions older that 0.9.1 at this time. That would be too much work. But moving forward this should be something that is top of mind, and a process that adheres to typical development processes needs to be established.

**Comment by jlprevatt** [comment]
Isolated this issue to the concept of creating a snapshot of one previous version of the documentation that is downloadable (see #106). Other ideas discussed in this issue should be created as other issues for sizing and etc.
