### ISSUE TITLE
Document password requirements for upgrading with qpc-tools

### ISSUE THREAD

**Issue by myersCody** [quipucords/quipudocs#105]
We need to document that if you are going to use qpc-tools to upgrade to a new version of the server, that you must provide the SAME password and username for the database or you may experience data loss. 

We especially need this documented for Discovery downstream, its one of the issues we found during testing.

**Comment by jlprevatt** [comment]
@myersCody 
For now, it looks like this information should be available in a minimum of 4 places:
proc-installing-scripted-offline-qpc-inst.adoc ("Installing the server" section)
proc-installing-scripted-online-inst.adoc ("Installing the server" section)
ref-tools-install-options-inst.adoc (2 places, in the definitions for `--db-user` and `--db-password`)
