### ISSUE TITLE
What is the earliest release of RHEL QPC works on ?

### ISSUE THREAD

**Issue by benneteapen** [quipucords/quipudocs#27]
The QPC doc on https://quipucords.readthedocs.io/en/0.0.46/requirements.html says, "You must install Quipucords on a system that is running Red Hat Enterprise Linux 6 or 7". But, I don't think it works fine on many releases of 6.x. I tried installing it on 6.1 and realized Red Hat does not support docker on 6.x.

It would be great to mention on the doc what is the earliest release of RHEL, on which QPC would work stable and without issues.

**Comment by kholdaway** [comment]
Documentation updated.
