### ISSUE TITLE
Typo in documentation (qpc_tools was used instead of qpc-tools)

### ISSUE THREAD

**Issue by benneteapen** [quipucords/quipudocs#97]
I noticed a typo in the documentation.

The command to install qpc-tools is given as :
### # yum install -y https ://github.com/quipucords/qpc- tools/releases/latest/download/**_qpc_tools_**.el7.noarch.rpm

It should be : 
### # yum install -y https ://github.com/quipucords/qpc-tools/releases/latest/download/**_qpc-tools_**.el7.noarch.rpm

The typo needs to be corrected for the qpc-tools install command on RHEL 6/7/8

**Comment by jlprevatt** [comment]
In the adoc source file for the Installing qpc-tools topic, this text is set from an attribute in the src/community/attributes/attributes-qpc.adoc file. The attribute value has been changed in that file, as shown by the following screen capture.

![image](https://user-images.githubusercontent.com/31351227/68790870-28191100-0616-11ea-92c5-6a34838b2449.png)

**Comment by jlprevatt** [comment]
I also did a search of the qpc install guide and those are the only 3 instances of "qpc_tools" found by the search.
